# Generated by Django 3.2.16 on 2024-05-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='fof', help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', verbose_name='Идентификатор'),
        ),
    ]
