# Generated by Django 3.2.16 on 2024-05-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.TextField(default='10', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='item',
            name='density',
            field=models.TextField(default='10', verbose_name='Плотность'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_width',
            field=models.TextField(default='10', verbose_name='Ширина полотна'),
        ),
        migrations.AddField(
            model_name='item',
            name='made_in',
            field=models.TextField(default='10', verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.TextField(default='10', verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='item',
            name='type_fabric',
            field=models.TextField(default='10', verbose_name='Тип ткани'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор'),
        ),
    ]
