# Generated by Django 3.2.16 on 2024-05-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20240529_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_opt',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
