# Generated by Django 3.2.16 on 2024-05-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_item_price_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images', verbose_name='Фото'),
        ),
    ]
